include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  errors:
    todo: ignore
    fixme: ignore
  exclude:
    - .fvm/**
    - '**/*.g.dart'

custom_lint:
  rules:

linter:
  rules:
    - avoid_print
    - avoid_void_async
    - await_only_futures
    - always_use_package_imports
    - always_put_required_named_parameters_first
    - avoid_empty_else
    - avoid_returning_null_for_void
    - close_sinks
    - lines_longer_than_80_chars
    - prefer_single_quotes
    - prefer_final_in_for_each
    - require_trailing_commas
    - use_build_context_synchronously
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - unnecessary_parenthesis
    - unnecessary_to_list_in_spreads
    - use_colored_box
    - use_decorated_box

