import 'package:countmein/domain/entities/nation.dart';

final nations = <Nation>[
  Nation('AFGHANISTAN', 'Z200'),
  Nation('AFRICA DEL SUD-OVEST', 'Z300'),
  Nation('ALBANIA', 'Z100'),
  Nation('ALGERIA', 'Z301'),
  Nation('ANDORRA', 'Z101'),
  Nation('ANGOLA', 'Z302'),
  Nation('ANGUILLA (ISOLA)', 'Z529'),
  Nation('ANTIGUA E BARBUDA', 'Z532'),
  Nation('ANTILLE BRITANNICHE', 'Z500'),
  Nation('ANTILLE BRITANNICHE', 'Z521'),
  Nation('ANTILLE BRITANNICHE', 'Z523'),
  Nation('ANTILLE OLANDESI', 'Z501'),
  Nation('ARABIA MERIDIONALE FEDERAZIONE', 'Z201'),
  Nation('ARABIA MERIDIONALE PROTETTORATO', 'Z202'),
  Nation('ARABIA SAUDITA', 'Z203'),
  Nation('ARGENTINA', 'Z600'),
  Nation('ARMENIA', 'Z137'),
  Nation('ARMENIA', 'Z252'),
  Nation('AUSTRALIA', 'Z700'),
  Nation('AUSTRIA', 'Z102'),
  Nation('AZERBAIGIAN', 'Z141'),
  Nation('AZERBAIGIAN', 'Z253'),
  Nation('BAHAMA (ISOLE)', 'Z502'),
  Nation('BAHAMAS', 'Z502'),
  Nation('BAHREIN', 'Z204'),
  Nation('BANGLADESH', 'Z249'),
  Nation('BARBADOS', 'Z522'),
  Nation('BASUTOLAND-SUD AFRICA BRITANNICO', 'Z303'),
  Nation('BECIUANIA-SUD AFRICA BRITANNICO', 'Z304'),
  Nation('BELGIO', 'Z103'),
  Nation('BELIZE', 'Z512'),
  Nation('BENIN', 'Z314'),
  Nation('BERMUDA (ISOLE)', 'Z400'),
  Nation('BHUTAN', 'Z205'),
  Nation('BIELORUSSIA', 'Z139'),
  Nation('BIRMANIA', 'Z206'),
  Nation('BOLIVIA', 'Z601'),
  Nation('BOPHUTHATSWANA', 'Z364'),
  Nation('BOSNIA ED ERZEGOVINA', 'Z153'),
  Nation('BOTSWANA', 'Z358'),
  Nation('BRASILE', 'Z602'),
  Nation('BRUNEI', 'Z207'),
  Nation('BULGARIA', 'Z104'),
  Nation('BURKINA', 'Z354'),
  Nation('BURKINA FASO', 'Z354'),
  Nation('BURUNDI', 'Z305'),
  Nation('CAMBOGIA', 'Z208'),
  Nation('CAMERUN', 'Z306'),
  Nation('CANADA', 'Z401'),
  Nation('CAPO VERDE', 'Z307'),
  Nation('CAROLINE (ISOLE)', 'Z701'),
  Nation('CAYMAN (ISOLE)', 'Z530'),
  Nation('CECA REPUBBLICA', 'Z156'),
  Nation('CECOSLOVACCHIA', 'Z105'),
  Nation('CENTRAFRICANA REPUBBLICA', 'Z308'),
  Nation('CENTROAFRICANA REPUBBLICA', 'Z308'),
  Nation('CENTROAFRICANO IMPERO', 'Z308'),
  Nation('CEYLON', 'Z209'),
  Nation('CHRISTMAS (ISOLA)', 'Z702'),
  Nation('CIAD', 'Z309'),
  Nation('CILE', 'Z603'),
  Nation('CINA NAZIONALE', 'Z217'),
  Nation('CINA REPUBBLICA POPOLARE', 'Z210'),
  Nation('CIPRO', 'Z211'),
  Nation('CISKEI', 'Z367'),
  Nation("CITTA' DEL VATICANO", 'Z106'),
  Nation('COCOS (ISOLE)', 'Z212'),
  Nation('COLOMBIA', 'Z604'),
  Nation('COMORE (ISOLE)', 'Z310'),
  Nation('CONGO BRAZZAVILLE', 'Z311'),
  Nation('CONGO LEOPOLDVILLE', 'Z312'),
  Nation('CONGO REPUBBLICA DEMOCRATICA', 'Z312'),
  Nation('CONGO REPUBBLICA POPOLARE', 'Z311'),
  Nation('COOK (ISOLE)', 'Z703'),
  Nation('COREA DEL NORD', 'Z214'),
  Nation('COREA DEL SUD', 'Z213'),
  Nation("COSTA D'AVORIO", 'Z313'),
  Nation('COSTA DEI PIRATI=TRUCIAL STATES', 'Z215'),
  Nation('COSTA RICA', 'Z503'),
  Nation('CROAZIA', 'Z149'),
  Nation('CUBA', 'Z504'),
  Nation('DAHOMEY=BENIN', 'Z314'),
  Nation('DANIMARCA', 'Z107'),
  Nation('DIPENDENZE AUSTRALIANE', 'Z900'),
  Nation('DIPENDENZE BRITANNICHE', 'Z901'),
  Nation('DIPENDENZE CANADESI', 'Z800'),
  Nation('DIPENDENZE FRANCESI', 'Z902'),
  Nation('DIPENDENZE NEOZELANDESI', 'Z903'),
  Nation('DIPENDENZE NORVEGESI ANTARTICHE', 'Z904'),
  Nation('DIPENDENZE NORVEGESI ARTICHE', 'Z801'),
  Nation('DIPENDENZE RUSSE', 'Z802'),
  Nation('DIPENDENZE SOVIETICHE', 'Z802'),
  Nation('DIPENDENZE STATUNITENSI', 'Z905'),
  Nation('DIPENDENZE SUDAFRICANE', 'Z906'),
  Nation('DOMINICA', 'Z526'),
  Nation('DOMINICANA REPUBBLICA', 'Z505'),
  Nation('ECUADOR', 'Z605'),
  Nation('EGITTO', 'Z336'),
  Nation('EL SALVADOR', 'Z506'),
  Nation('EMIRATI ARABI UNITI', 'Z215'),
  Nation('ERITREA', 'Z368'),
  Nation('ESTONIA', 'Z144'),
  Nation('ETIOPIA', 'Z315'),
  Nation('FAER OER (ISOLE)', 'Z108'),
  Nation('FALKLAND (ISOLE)', 'Z609'),
  Nation('FEDERAZIONE RUSSA', 'Z154'),
  Nation('FIGI=VITI', 'Z704'),
  Nation('FILIPPINE', 'Z216'),
  Nation('FINLANDIA', 'Z109'),
  Nation('FORMOSA=TAIWAN', 'Z217'),
  Nation('FRANCIA', 'Z110'),
  Nation('GABON', 'Z316'),
  Nation('GAMBIA', 'Z317'),
  Nation('GAZA (TERRITORIO DI)', 'Z218'),
  Nation('GEORGIA', 'Z136'),
  Nation('GEORGIA', 'Z254'),
  Nation('GERMANIA', 'Z112'),
  Nation('GERMANIA REPUBBLICA DEMOCRATICA', 'Z111'),
  Nation('GERMANIA REPUBBLICA FEDERALE', 'Z112'),
  Nation('GHANA', 'Z318'),
  Nation('GIAMAICA', 'Z507'),
  Nation('GIAPPONE', 'Z219'),
  Nation('GIBILTERRA', 'Z113'),
  Nation('GIBUTI', 'Z361'),
  Nation('GILBERT E ELLICE (ISOLE)', 'Z705'),
  Nation('GIORDANIA', 'Z220'),
  Nation('GRAN BRETAGNA E IRLANDA DEL NORD', 'Z114'),
  Nation('GRECIA', 'Z115'),
  Nation('GRENADA', 'Z524'),
  Nation('GROENLANDIA', 'Z402'),
  Nation('GUADALUPA', 'Z508'),
  Nation('GUAM (ISOLA)', 'Z706'),
  Nation('GUATEMALA', 'Z509'),
  Nation('GUAYANA OLANDESE', 'Z608'),
  Nation('GUAYANA=GUYANA FRANCESE', 'Z607'),
  Nation('GUIANA FRANCESE', 'Z607'),
  Nation('GUINEA', 'Z319'),
  Nation('GUINEA BISSAU', 'Z320'),
  Nation('GUINEA EQUATORIALE', 'Z321'),
  Nation('GUINEA PORTOGHESE', 'Z320'),
  Nation('GUINEA SPAGNOLA', 'Z321'),
  Nation('GUYANA', 'Z606'),
  Nation('GUYANA BRITANNICA', 'Z606'),
  Nation('HAITI', 'Z510'),
  Nation('HONDURAS', 'Z511'),
  Nation('HONDURAS BRITANNICO', 'Z512'),
  Nation('HONG KONG', 'Z221'),
  Nation('IFNI', 'Z323'),
  Nation('INDIA', 'Z222'),
  Nation('INDONESIA', 'Z223'),
  Nation('IRAN', 'Z224'),
  Nation('IRAQ', 'Z225'),
  Nation('IRIAN OCCIDENTALE', 'Z707'),
  Nation('IRLANDA', 'Z116'),
  Nation('ISLANDA', 'Z117'),
  Nation('ISOLE CILENE (PASQUA E SALA Y GOMEZ)', 'Z721'),
  Nation('ISOLE DEL CANALE', 'Z124'),
  Nation("ISOLE DELL'UNIONE", 'Z727'),
  Nation('ISRAELE', 'Z226'),
  Nation('IUGOSLAVIA', 'Z118'),
  Nation('KAZAKHSTAN', 'Z255'),
  Nation('KAZAKISTAN', 'Z152'),
  Nation('KAZAKISTAN', 'Z255'),
  Nation('KENYA', 'Z322'),
  Nation('KIRGHIZISTAN', 'Z142'),
  Nation('KIRGHIZISTAN', 'Z256'),
  Nation('KIRIBATI', 'Z731'),
  Nation('KOSOVO', 'Z160'),
  Nation('KUWAIT', 'Z227'),
  Nation('LA REUNION (ISOLA)', 'Z324'),
  Nation('LAOS', 'Z228'),
  Nation('LESOTHO', 'Z359'),
  Nation('LETTONIA', 'Z145'),
  Nation('LIBANO', 'Z229'),
  Nation('LIBERIA', 'Z325'),
  Nation('LIBIA', 'Z326'),
  Nation('LIECHTENSTEIN', 'Z119'),
  Nation('LITUANIA', 'Z146'),
  Nation('LUSSEMBURGO', 'Z120'),
  Nation('MACAO', 'Z231'),
  Nation('MACEDONIA', 'Z148'),
  Nation('MACEDONIA DEL NORD', 'Z148'),
  Nation('MACQUARIE (ISOLE)', 'Z708'),
  Nation('MADAGASCAR', 'Z327'),
  Nation('MALAWI', 'Z328'),
  Nation('MALAYSIA', 'Z230'),
  Nation('MALAYSIA', 'Z247'),
  Nation('MALDIVE', 'Z232'),
  Nation('MALI', 'Z329'),
  Nation('MALTA', 'Z121'),
  Nation('MALVINE=FALKLAND (ISOLE)', 'Z609'),
  Nation('MAN (ISOLA)', 'Z122'),
  Nation('MARCUS (ISOLE)', 'Z709'),
  Nation('MARIANNE (ISOLE)', 'Z710'),
  Nation('MAROCCO', 'Z330'),
  Nation('MARSHALL (ISOLE)', 'Z711'),
  Nation('MARTINICA', 'Z513'),
  Nation('MAURITANIA', 'Z331'),
  Nation('MAURIZIO (ISOLE)', 'Z332'),
  Nation('MAYOTTE (ISOLA)', 'Z360'),
  Nation('MESSICO', 'Z514'),
  Nation('MICRONESIA STATI FEDERATI', 'Z735'),
  Nation('MIDWAY (ISOLE)', 'Z712'),
  Nation('MOLDAVIA', 'Z140'),
  Nation('MONACO', 'Z123'),
  Nation('MONGOLIA', 'Z233'),
  Nation('MONTENEGRO', 'Z159'),
  Nation('MONTSERRAT', 'Z531'),
  Nation('MOZAMBICO', 'Z333'),
  Nation('MYANMAR', 'Z206'),
  Nation('NAMIBIA', 'Z300'),
  Nation('NAURU (ISOLE)', 'Z713'),
  Nation('NEPAL', 'Z234'),
  Nation('NICARAGUA', 'Z515'),
  Nation('NIGER', 'Z334'),
  Nation('NIGERIA', 'Z335'),
  Nation('NIUE=SAVAGE (ISOLE)', 'Z714'),
  Nation('NORFOLK (ISOLE E ISOLE DEL MAR DEI CORALLI)', 'Z715'),
  Nation('NORMANNE (ISOLE)=ISOLE DEL CANALE', 'Z124'),
  Nation('NORVEGIA', 'Z125'),
  Nation('NUOVA CALEDONIA (ISOLE E DIPENDENZE)', 'Z716'),
  Nation('NUOVA GUINEA', 'Z718'),
  Nation('NUOVA ZELANDA', 'Z719'),
  Nation('NUOVE EBRIDI (ISOLE CONDOMINIO FRANCO-INGLESE)', 'Z717'),
  Nation('OMAN', 'Z235'),
  Nation('PAESI BASSI', 'Z126'),
  Nation('PAKISTAN', 'Z236'),
  Nation('PALAU REPUBBLICA', 'Z734'),
  Nation('PANAMA', 'Z516'),
  Nation('PANAMA ZONA DEL CANALE', 'Z517'),
  Nation('PAPUA NUOVA GUINEA', 'Z730'),
  Nation('PAPUASIA', 'Z720'),
  Nation('PARAGUAY', 'Z610'),
  Nation('PASQUA (ISOLA)', 'Z721'),
  Nation("PERU'", 'Z611'),
  Nation('PITCAIRN (E DIPENDENZE)', 'Z722'),
  Nation('POLINESIA FRANCESE (ISOLE)', 'Z723'),
  Nation('POLONIA', 'Z127'),
  Nation('PORTOGALLO', 'Z128'),
  Nation('PUERTO RICO', 'Z518'),
  Nation('QATAR', 'Z237'),
  Nation('REGNO UNITO', 'Z114'),
  Nation('REPUBBLICA CECA', 'Z156'),
  Nation('REPUBBLICA DI COREA', 'Z213'),
  Nation('REPUBBLICA DI POLONIA', 'Z127'),
  Nation('REPUBBLICA DOMINICANA', 'Z505'),
  Nation('RHODESIA', 'Z337'),
  Nation('ROMANIA', 'Z129'),
  Nation('RUANDA', 'Z338'),
  Nation('RUSSIA=FEDERAZIONE RUSSA', 'Z154'),
  Nation('RYUKYU (ISOLE)', 'Z238'),
  Nation('SAHARA MERIDIONALE', 'Z362'),
  Nation('SAHARA SETTENTRIONALE', 'Z363'),
  Nation('SAHARA SPAGNOLO', 'Z339'),
  Nation('SAINT KITTS E NEVIS', 'Z533'),
  Nation('SAINT LUCIA', 'Z527'),
  Nation('SAINT PIERRE ET MIQUELON (ISOLE)', 'Z403'),
  Nation('SAINT VINCENT E GRENADINE', 'Z528'),
  Nation('SALOMONE (ISOLE)', 'Z724'),
  Nation('SAMOA', 'Z726'),
  Nation('SAMOA AMERICANE (ISOLE)', 'Z725'),
  Nation('SAN MARINO', 'Z130'),
  Nation("SANT'ELENA (ISOLA)", 'Z340'),
  Nation("SAO TOME' E PRINCIPE (ISOLE)", 'Z341'),
  Nation('SAVAGE (ISOLE)', 'Z714'),
  Nation('SEICELLE (ISOLE)', 'Z342'),
  Nation('SENEGAL', 'Z343'),
  Nation('SERBIA', 'Z158'),
  Nation('SERBIA E MONTENEGRO', 'Z157'),
  Nation('SIERRA LEONE', 'Z344'),
  Nation('SIKKIM', 'Z239'),
  Nation('SINGAPORE', 'Z248'),
  Nation('SIRIA', 'Z240'),
  Nation('SLOVACCHIA', 'Z155'),
  Nation('SLOVENIA', 'Z150'),
  Nation('SOMALIA', 'Z345'),
  Nation('SOMALIA FRANCESE', 'Z346'),
  Nation('SPAGNA', 'Z131'),
  Nation('SRI LANKA', 'Z209'),
  Nation("STATI UNITI D'AMERICA", 'Z404'),
  Nation('SUD SUDAN', 'Z907'),
  Nation('SUDAFRICANA REPUBBLICA', 'Z347'),
  Nation('SUDAN', 'Z348'),
  Nation('SURINAME', 'Z608'),
  Nation('SVEZIA', 'Z132'),
  Nation('SVIZZERA', 'Z133'),
  Nation('SWAZILAND', 'Z349'),
  Nation('TAGIKISTAN', 'Z147'),
  Nation('TAGIKISTAN', 'Z257'),
  Nation('TAIWAN', 'Z217'),
  Nation('TANGANICA', 'Z350'),
  Nation('TANZANIA', 'Z357'),
  Nation('TERRITORI PALESTINESI', 'Z161'),
  Nation('TERRITORIO FRANCESE DEGLI AFAR E DEGLI ISSA', 'Z346'),
  Nation('THAILANDIA', 'Z241'),
  Nation('TIMOR (ISOLA)', 'Z242'),
  Nation('TOGO', 'Z351'),
  Nation("TOKELAU=ISOLE DELL'UNIONE", 'Z727'),
  Nation('TONGA', 'Z728'),
  Nation('TRANSKEI', 'Z365'),
  Nation('TRINIDAD E TOBAGO', 'Z612'),
  Nation('TUNISIA', 'Z352'),
  Nation('TURCHIA', 'Z243'),
  Nation('TURKMENISTAN', 'Z151'),
  Nation('TURKMENISTAN', 'Z258'),
  Nation('TURKS E CAICOS (ISOLE)', 'Z519'),
  Nation('TUVALU', 'Z732'),
  Nation('UCRAINA', 'Z138'),
  Nation('UGANDA', 'Z353'),
  Nation('UNGHERIA', 'Z134'),
  Nation('UNIONE REPUBBLICHE SOCIALISTE SOVIETICHE', 'Z135'),
  Nation('URUGUAY', 'Z613'),
  Nation('UZBEKISTAN', 'Z143'),
  Nation('UZBEKISTAN', 'Z259'),
  Nation('VANUATU', 'Z733'),
  Nation('VENDA', 'Z366'),
  Nation('VENEZUELA', 'Z614'),
  Nation('VERGINI AMERICANE (ISOLE)', 'Z520'),
  Nation('VERGINI BRITANNICHE (ISOLE)', 'Z525'),
  Nation('VIETNAM', 'Z251'),
  Nation('VIETNAM DEL NORD', 'Z245'),
  Nation('VIETNAM DEL SUD', 'Z244'),
  Nation('VITI', 'Z704'),
  Nation('VOLTA=ALTOVOLTA', 'Z354'),
  Nation('WALLIS E FUTUNA (ISOLE)', 'Z729'),
  Nation('YEMEN', 'Z246'),
  Nation('YEMEN REPUBBLICA DEMOCRATICA POPOLARE', 'Z250'),
  Nation('ZAIRE', 'Z312'),
  Nation('ZAMBIA', 'Z355'),
  Nation('ZANZIBAR', 'Z356'),
  Nation('ZIMBABWE', 'Z337'),
];
